### ISSUE TITLE
Tasks to try to get this theme ready for public consumption

### ISSUE THREAD

**Issue by andrewserong** [andrewserong/dark-pastel-theme#1]
## Tasks

* [x] Replace the three ornaments with some handmade ones of my own, so that it has a unique feel
* [x] Remove all unused patterns and template parts
* [x] Work through each of the templates and make sure they're looking good
* [x] Flesh out a homepage template, and see what sorts of patterns can be pulled from it
* [x] Include an optional tile-based layout for blog posts
* [x] Create color variations
* [x] Create Query loop patterns (frames and no frames)
  * [x] Tiles with Title and Date
  * [x] Simple list of Post Title and Date
* [x] Create Page layout patterns (about page)
* [x] Test across browsers, and virtually on iOS and Android
* [x] Remove all the TT2 styling rules, and check that they don't need replacements
* [x] Add root padding
* [x] Use the new use root padding aware alignments feature
* [x] Update the spacing presets of the theme
* [x] Update all the patterns to use the desired padding
* [x] Copy the padding, line-height, etc, from the home template into the patterns
* [x] Update index template
* [x] Tweak colours of variations (what about secondary / tertiary colours — do we use them anywhere?)
* [x] Update secondary colours in style variations
* [x] Once updated, update all the templates again
* [x] Add screenshot(s) (1200 x 900 px, png)
* [x] Update metadata
* [x] Update where patterns are stored: https://developer.wordpress.org/themes/advanced-topics/block-patterns/

**Comment by andrewserong** [comment]
Pretty much everything appears to be covered now, and I've tested on iOS and Android. I think this is in decent enough shape for an MVP, so closing out this issue now.
